[project]
name = "fastapi-tutorial"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Saiken Ho", email = "saikenhh@gmail.com" }
]
requires-python = ">=3.11"
dependencies = [
    "aiosqlite>=0.22.1",
    "fastapi[standard]>=0.142.2",
    "imagekit-python>=0.0.1a1",
    "imagekitio>=5.10.0",
    "python-dotenv>=1.2.4",
    "sqlalchemy[asyncio]>=2.1.2",
    "uvicorn>=0.54.0",
]

[project.scripts]
fastapi-tutorial = "fastapi_tutorial:main"

[build-system]
requires = ["uv_build>=0.12.8,<0.13.0"]
build-backend = "uv_build"
